//
//  Contacts.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class Contacts: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _emailId: String?
    var _score: String?
    var _status: String?
    
    class func dynamoDBTableName() -> String {

        return "myfirstawsmobile-mobilehub-1522717300-Contacts"
    }
    
    class func hashKeyAttribute() -> String {

        return "_emailId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_emailId" : "email_id",
               "_score":"score",
               "_status": "status"
        ]
    }
}
