//
//  PollChoices.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class PollChoices: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _pollId: String?
    var _questionId: String?
    var _choice: String?
    
    class func dynamoDBTableName() -> String {

        return "myfirstawsmobile-mobilehub-1522717300-PollChoices"
    }
    
    class func hashKeyAttribute() -> String {

        return "_pollId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_questionId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_pollId" : "poll_id",
               "_questionId" : "question_id",
               "_choice" : "choice",
        ]
    }
}
